server:
  port: ${PORT}

spring:
  application:
    name: TypeAheadSearch

  data:
    mongodb:
      host: localhost
      port: 27017
      database: search_ahead_db
      auto-index-creation: true

    redis:
      host: localhost
      port: 6379

# Logging Configuration - MongoDB Query Logging
logging:
  level:
    root: INFO
    com.example.TypeAheadSearch: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG